{% set name = "epicscorelibs" %}
{% set version = "7.0.10.99.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d21c84807bb329f4b8752d1c9638a4e60f42df2dc837b6286f0b2d5515129a3d

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-binary :all: -vv'

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - setuptools_dso >=2.9a1
    - readline  # [not win]
  run:
    - python
    - setuptools_dso >=2.9a1
    - readline  # [not win]
    - numpy

test:
  imports:
    - epicscorelibs
    - epicscorelibs.ca
    - epicscorelibs.ca.dbr
    - epicscorelibs.config

about:
  home: https://github.com/mdavidsaver/epicscorelibs
  license: EPICS
  license_file: LICENSE
  summary: EPICS core libraries packaged as a "python" module
  description: |
    The EPICS (Experimental Physics and Industrial Control System) core
    libraries for use by python modules. Either dynamically with ctypes
    or statically by compiled extension.

extra:
  recipe-maintainers:
    - hhslepicka
    - klauer
    - mrakitin
