{% set name = "epicscorelibs" %}
{% set version = "7.0.7.99.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d08cd4b228d7087fd172b9b48d5ebc1c763b6c1fbda26369776d5b274f1c73b4

build:
  number: 1
  script: '{{ PYTHON }} -m pip install . --no-binary :all: -vv'

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - setuptools_dso
    - readline  # [not win]
  run:
    - python
    - setuptools_dso
    - readline  # [not win]

test:
  imports:
    - epicscorelibs
    - epicscorelibs.config

about:
  home: https://github.com/mdavidsaver/epicscorelibs
  license: EPICS
  license_file: LICENSE
  summary: EPICS core libraries packaged as a "python" module
  description: |
    The EPICS (Experimental Physics and Industrial Control System) core
    libraries for use by python modules. Either dynamically with ctypes
    or statically by compiled extension.

extra:
  recipe-maintainers:
    - hhslepicka
    - klauer
