{% set name = "epicscorelibs" %}
{% set version = "7.0.4.99.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9d8581621e5bf7b5a6b9e6d8891cc48db0b8dbf09cdf39b348080a6e90508c73

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-binary :all: -vv'

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - setuptools_dso
    - readline  # [not win]
  run:
    - python
    - readline  # [not win]

test:
  imports:
    - epicscorelibs
    - epicscorelibs.config

about:
  home: https://github.com/mdavidsaver/epicscorelibs
  license: EPICS Open
  license_file: LICENSE
  summary: EPICS core libraries packaged as a "python" module
  description: |
    The EPICS (Experimental Physics and Industrial Control System) core
    libraries for use by python modules. Either dynamically with ctypes
    or statically by compiled extension.

extra:
  recipe-maintainers:
    - hhslepicka
