travis:
  secure:
    BINSTAR_TOKEN: cx1F8BoRgynOwn+s3Do48S9R+8uzjNKW/05bjYz4fH1U91CVCajAT4MhE93AAD15Ou40aWZ9scQo0CpwkER/BFA8r79pQTyoHMIALGsPBWOJlN0jztyq+U/XLtBDkWKALCMagH4Ns6onEx1f5t6yMtWntF2LLaO/4zEuKN42WZ36UOvZlkhZGIrk4fIKN8srtvy3SSycTO8nvsiUtZdaTMSYTlyNILH110KHaDrCKzYmkgr+VV1BW8VgpxeFSNx6uVYlZs3GjHWw4oWCX5yJaXaFWlvecyqOFIBMtNT2U/BN4O6OK8VEqHtyTOgcOnT1mEST6GcONzSJko0zkWhrqQb8zsP8TQocj3WbAplECKcvseT1nkS+wqQEUb+vzHSu56iJST6F8fL1mIrIoSQcyxxfmET+AevdeyjzT/CBWKDJ7r5wYwe48fV1JJSjgt+FGxn4pa8krxSkqrgqg9L92hSUWYqMGPx8bzP4RcKnLPJmdUt5c6ClDtaqTKq5VCXfMH6MruhxKzGL2IWa0784u4d/X4eRakYDefSgh5N0W9C3FVEP6V4jTz4cx2TJKWUF5jchdhTwL5fBpTlZtR/dybE9rhYs3/VU29a/B8CzpwV9DK0y2439iwnS6wTXbsKtAj2A8JzAszmXJuRb2fRozj6ZkdpARqv+4Acn6zsghk4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
